/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bugbusterlibrary.ui;

import java.awt.Color;
import java.sql.*;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import bugbusterlibrary.entity.*;
import java.awt.HeadlessException;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
/**
 *
 * @author Sango
 */
public class BugBusterLibraryUI extends javax.swing.JFrame {
    
    EntityManagerFactory emf=Persistence.createEntityManagerFactory("BugBusterLibraryPU");  
    EntityManager em=emf.createEntityManager();
    /**
     * Creates new form BugBusterLibraryUI
     */
    public BugBusterLibraryUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        LogInPane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogInPassword = new javax.swing.JPasswordField();
        LogInUsername = new javax.swing.JTextField();
        LogInButtonPane = new javax.swing.JPanel();
        LogInbutton = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ToRegister = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        HeadNamePane4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        RegistrationPane = new javax.swing.JPanel();
        HeadNamePane3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        RegName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        RegLname = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        regId = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        RegPassword = new javax.swing.JPasswordField();
        RegReEnterpassword = new javax.swing.JPasswordField();
        RegSignUp = new javax.swing.JPanel();
        RegSingUpText = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        RegBack = new javax.swing.JPanel();
        RegBackText = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RegUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        regEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        regRoleStudent = new javax.swing.JRadioButton();
        regRoleAdmin = new javax.swing.JRadioButton();
        MenuPane = new javax.swing.JPanel();
        HeadNamePane2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LogOutButton = new javax.swing.JLabel();
        UserLoggedInName = new javax.swing.JLabel();
        SideOptionPane = new javax.swing.JPanel();
        BookOption = new javax.swing.JPanel();
        BooksOptionText = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        MyBooksOption = new javax.swing.JPanel();
        MyBooksOptionText = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        AboutOption = new javax.swing.JPanel();
        AboutOptionText = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ContentPane = new javax.swing.JPanel();
        BooksCategoryContent = new javax.swing.JPanel();
        Books = new javax.swing.JPanel();
        Categories = new javax.swing.JPanel();
        Category_Heading = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        BookList = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        SelectedBook = new javax.swing.JPanel();
        BookInfo = new javax.swing.JPanel();
        Reciept = new javax.swing.JPanel();
        MyBooksContent = new javax.swing.JPanel();
        AboutContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BugBuster Library");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        LogInPane.setBackground(new java.awt.Color(62, 61, 88));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Username:");

        LogInButtonPane.setBackground(new java.awt.Color(255, 255, 255));
        LogInButtonPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 61, 88)));

        LogInbutton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LogInbutton.setText("Log In");
        LogInbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LogInbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogInbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogInbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogInbuttonMousePressed(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/login_rounded_right_25px.png"))); // NOI18N

        javax.swing.GroupLayout LogInButtonPaneLayout = new javax.swing.GroupLayout(LogInButtonPane);
        LogInButtonPane.setLayout(LogInButtonPaneLayout);
        LogInButtonPaneLayout.setHorizontalGroup(
            LogInButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInButtonPaneLayout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogInbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LogInButtonPaneLayout.setVerticalGroup(
            LogInButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogInbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        ToRegister.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ToRegister.setForeground(new java.awt.Color(0, 153, 153));
        ToRegister.setText("Not a member? register.");
        ToRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToRegisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToRegister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(ToRegister)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Password:");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gender_neutral_user_40px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("LOG IN TO YOUR ACCOUNT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LogInButtonPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LogInUsername)
                                .addComponent(LogInPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(176, 176, 176))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LogInUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogInPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(LogInButtonPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        HeadNamePane4.setBackground(new java.awt.Color(62, 61, 88));
        HeadNamePane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("BugBuster Library");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/library_30px.png"))); // NOI18N

        javax.swing.GroupLayout HeadNamePane4Layout = new javax.swing.GroupLayout(HeadNamePane4);
        HeadNamePane4.setLayout(HeadNamePane4Layout);
        HeadNamePane4Layout.setHorizontalGroup(
            HeadNamePane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadNamePane4Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(HeadNamePane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeadNamePane4Layout.createSequentialGroup()
                    .addGap(290, 290, 290)
                    .addComponent(jLabel23)
                    .addContainerGap(291, Short.MAX_VALUE)))
        );
        HeadNamePane4Layout.setVerticalGroup(
            HeadNamePane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadNamePane4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel25)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(HeadNamePane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeadNamePane4Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel23)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout LogInPaneLayout = new javax.swing.GroupLayout(LogInPane);
        LogInPane.setLayout(LogInPaneLayout);
        LogInPaneLayout.setHorizontalGroup(
            LogInPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInPaneLayout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
            .addComponent(HeadNamePane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LogInPaneLayout.setVerticalGroup(
            LogInPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInPaneLayout.createSequentialGroup()
                .addComponent(HeadNamePane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        getContentPane().add(LogInPane, "card2");

        RegistrationPane.setBackground(new java.awt.Color(255, 255, 255));

        HeadNamePane3.setBackground(new java.awt.Color(62, 61, 88));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("BugBuster Library");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/library_30px.png"))); // NOI18N

        javax.swing.GroupLayout HeadNamePane3Layout = new javax.swing.GroupLayout(HeadNamePane3);
        HeadNamePane3.setLayout(HeadNamePane3Layout);
        HeadNamePane3Layout.setHorizontalGroup(
            HeadNamePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadNamePane3Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(HeadNamePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeadNamePane3Layout.createSequentialGroup()
                    .addGap(290, 290, 290)
                    .addComponent(jLabel14)
                    .addContainerGap(301, Short.MAX_VALUE)))
        );
        HeadNamePane3Layout.setVerticalGroup(
            HeadNamePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadNamePane3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(HeadNamePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeadNamePane3Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel14)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("First name:");

        RegName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegNameActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Last name:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Id:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Password:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Re-enter password:");

        RegSignUp.setBackground(new java.awt.Color(255, 255, 255));
        RegSignUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 61, 88)));

        RegSingUpText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RegSingUpText.setText("Sign up");
        RegSingUpText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegSingUpTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegSingUpTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegSingUpTextMouseExited(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/login_rounded_right_25px.png"))); // NOI18N

        javax.swing.GroupLayout RegSignUpLayout = new javax.swing.GroupLayout(RegSignUp);
        RegSignUp.setLayout(RegSignUpLayout);
        RegSignUpLayout.setHorizontalGroup(
            RegSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegSignUpLayout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegSingUpText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        RegSignUpLayout.setVerticalGroup(
            RegSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegSignUpLayout.createSequentialGroup()
                .addComponent(RegSingUpText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        RegBack.setBackground(new java.awt.Color(255, 255, 255));
        RegBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 61, 88)));

        RegBackText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RegBackText.setText("Back");
        RegBackText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegBackTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegBackTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegBackTextMouseExited(evt);
            }
        });

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/left_arrow_25px.png"))); // NOI18N

        javax.swing.GroupLayout RegBackLayout = new javax.swing.GroupLayout(RegBack);
        RegBack.setLayout(RegBackLayout);
        RegBackLayout.setHorizontalGroup(
            RegBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegBackLayout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegBackText, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        RegBackLayout.setVerticalGroup(
            RegBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegBackText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gender_neutral_user_60px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Username:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("CREATE A NEW ACCOUNT");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("E-mail:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Role:");

        regRoleStudent.setText("Student");

        regRoleAdmin.setText("Admin");

        javax.swing.GroupLayout RegistrationPaneLayout = new javax.swing.GroupLayout(RegistrationPane);
        RegistrationPane.setLayout(RegistrationPaneLayout);
        RegistrationPaneLayout.setHorizontalGroup(
            RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeadNamePane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationPaneLayout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationPaneLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(RegBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(RegSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(RegistrationPaneLayout.createSequentialGroup()
                            .addComponent(jSeparator3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(RegistrationPaneLayout.createSequentialGroup()
                            .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel19)
                                .addComponent(jLabel18)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel4)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22))
                            .addGap(18, 18, 18)
                            .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(regEmail)
                                .addComponent(RegName)
                                .addComponent(RegLname)
                                .addComponent(regId)
                                .addComponent(RegUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RegReEnterpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(RegistrationPaneLayout.createSequentialGroup()
                                    .addComponent(regRoleStudent)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(regRoleAdmin)))
                            .addGap(23, 23, 23))))
                .addGap(244, 244, 244))
            .addGroup(RegistrationPaneLayout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegistrationPaneLayout.setVerticalGroup(
            RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationPaneLayout.createSequentialGroup()
                .addComponent(HeadNamePane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(RegName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(RegLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(regId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(regRoleStudent)
                    .addComponent(regRoleAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(RegUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(RegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(RegReEnterpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        getContentPane().add(RegistrationPane, "card4");

        MenuPane.setBackground(new java.awt.Color(102, 102, 102));

        HeadNamePane2.setBackground(new java.awt.Color(62, 61, 88));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BugBuster Library");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/library_30px.png"))); // NOI18N

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("User:");

        LogOutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogOutButton.setText("Log out");
        LogOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseExited(evt);
            }
        });

        UserLoggedInName.setForeground(new java.awt.Color(0, 204, 153));

        javax.swing.GroupLayout HeadNamePane2Layout = new javax.swing.GroupLayout(HeadNamePane2);
        HeadNamePane2.setLayout(HeadNamePane2Layout);
        HeadNamePane2Layout.setHorizontalGroup(
            HeadNamePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadNamePane2Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HeadNamePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadNamePane2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserLoggedInName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadNamePane2Layout.createSequentialGroup()
                        .addComponent(LogOutButton)
                        .addGap(62, 62, 62))))
            .addGroup(HeadNamePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeadNamePane2Layout.createSequentialGroup()
                    .addGap(290, 290, 290)
                    .addComponent(jLabel8)
                    .addContainerGap(301, Short.MAX_VALUE)))
        );
        HeadNamePane2Layout.setVerticalGroup(
            HeadNamePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadNamePane2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(HeadNamePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(HeadNamePane2Layout.createSequentialGroup()
                        .addGroup(HeadNamePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(UserLoggedInName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LogOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
            .addGroup(HeadNamePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeadNamePane2Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel8)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );

        SideOptionPane.setBackground(new java.awt.Color(28, 86, 120));

        BookOption.setBackground(new java.awt.Color(255, 255, 255));

        BooksOptionText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BooksOptionText.setText("Books");
        BooksOptionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BooksOptionTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BooksOptionTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BooksOptionTextMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sorting_answers_25px.png"))); // NOI18N

        javax.swing.GroupLayout BookOptionLayout = new javax.swing.GroupLayout(BookOption);
        BookOption.setLayout(BookOptionLayout);
        BookOptionLayout.setHorizontalGroup(
            BookOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookOptionLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BooksOptionText, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
        );
        BookOptionLayout.setVerticalGroup(
            BookOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BooksOptionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        MyBooksOption.setBackground(new java.awt.Color(255, 255, 255));

        MyBooksOptionText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MyBooksOptionText.setText("My books");
        MyBooksOptionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MyBooksOptionTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyBooksOptionTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyBooksOptionTextMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/books_25px.png"))); // NOI18N

        javax.swing.GroupLayout MyBooksOptionLayout = new javax.swing.GroupLayout(MyBooksOption);
        MyBooksOption.setLayout(MyBooksOptionLayout);
        MyBooksOptionLayout.setHorizontalGroup(
            MyBooksOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyBooksOptionLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyBooksOptionText, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        MyBooksOptionLayout.setVerticalGroup(
            MyBooksOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MyBooksOptionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        AboutOption.setBackground(new java.awt.Color(255, 255, 255));

        AboutOptionText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AboutOptionText.setText("About");
        AboutOptionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutOptionTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutOptionTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutOptionTextMouseExited(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/help_filled_25px.png"))); // NOI18N

        javax.swing.GroupLayout AboutOptionLayout = new javax.swing.GroupLayout(AboutOption);
        AboutOption.setLayout(AboutOptionLayout);
        AboutOptionLayout.setHorizontalGroup(
            AboutOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutOptionLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AboutOptionText, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
        );
        AboutOptionLayout.setVerticalGroup(
            AboutOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AboutOptionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SideOptionPaneLayout = new javax.swing.GroupLayout(SideOptionPane);
        SideOptionPane.setLayout(SideOptionPaneLayout);
        SideOptionPaneLayout.setHorizontalGroup(
            SideOptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideOptionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideOptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MyBooksOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideOptionPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AboutOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SideOptionPaneLayout.setVerticalGroup(
            SideOptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideOptionPaneLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BookOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MyBooksOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AboutOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ContentPane.setBackground(new java.awt.Color(255, 255, 255));
        ContentPane.setLayout(new java.awt.CardLayout());

        BooksCategoryContent.setBackground(new java.awt.Color(102, 102, 102));
        BooksCategoryContent.setLayout(new java.awt.CardLayout());

        Books.setBackground(new java.awt.Color(102, 102, 102));

        Categories.setBackground(new java.awt.Color(255, 255, 255));

        Category_Heading.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        Category_Heading.setText("Categories");

        javax.swing.GroupLayout CategoriesLayout = new javax.swing.GroupLayout(Categories);
        Categories.setLayout(CategoriesLayout);
        CategoriesLayout.setHorizontalGroup(
            CategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(CategoriesLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(Category_Heading)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        CategoriesLayout.setVerticalGroup(
            CategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CategoriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Category_Heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BookList.setBackground(new java.awt.Color(255, 255, 255));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel36.setText("Book list");

        jList1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout BookListLayout = new javax.swing.GroupLayout(BookList);
        BookList.setLayout(BookListLayout);
        BookListLayout.setHorizontalGroup(
            BookListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookListLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jLabel36)
                .addGap(106, 106, 106))
            .addComponent(jScrollPane1)
            .addGroup(BookListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
        );
        BookListLayout.setVerticalGroup(
            BookListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))
            .addGroup(BookListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BookListLayout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(402, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout BooksLayout = new javax.swing.GroupLayout(Books);
        Books.setLayout(BooksLayout);
        BooksLayout.setHorizontalGroup(
            BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
            .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BooksLayout.createSequentialGroup()
                    .addComponent(Categories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BookList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        BooksLayout.setVerticalGroup(
            BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
            .addGroup(BooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Categories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BookList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BooksCategoryContent.add(Books, "card2");

        BookInfo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BookInfoLayout = new javax.swing.GroupLayout(BookInfo);
        BookInfo.setLayout(BookInfoLayout);
        BookInfoLayout.setHorizontalGroup(
            BookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );
        BookInfoLayout.setVerticalGroup(
            BookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        Reciept.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout RecieptLayout = new javax.swing.GroupLayout(Reciept);
        Reciept.setLayout(RecieptLayout);
        RecieptLayout.setHorizontalGroup(
            RecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
        RecieptLayout.setVerticalGroup(
            RecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SelectedBookLayout = new javax.swing.GroupLayout(SelectedBook);
        SelectedBook.setLayout(SelectedBookLayout);
        SelectedBookLayout.setHorizontalGroup(
            SelectedBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectedBookLayout.createSequentialGroup()
                .addComponent(BookInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reciept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SelectedBookLayout.setVerticalGroup(
            SelectedBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BookInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Reciept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BooksCategoryContent.add(SelectedBook, "card3");

        ContentPane.add(BooksCategoryContent, "card2");

        MyBooksContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout MyBooksContentLayout = new javax.swing.GroupLayout(MyBooksContent);
        MyBooksContent.setLayout(MyBooksContentLayout);
        MyBooksContentLayout.setHorizontalGroup(
            MyBooksContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        MyBooksContentLayout.setVerticalGroup(
            MyBooksContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        ContentPane.add(MyBooksContent, "card3");

        AboutContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout AboutContentLayout = new javax.swing.GroupLayout(AboutContent);
        AboutContent.setLayout(AboutContentLayout);
        AboutContentLayout.setHorizontalGroup(
            AboutContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        AboutContentLayout.setVerticalGroup(
            AboutContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        ContentPane.add(AboutContent, "card4");

        javax.swing.GroupLayout MenuPaneLayout = new javax.swing.GroupLayout(MenuPane);
        MenuPane.setLayout(MenuPaneLayout);
        MenuPaneLayout.setHorizontalGroup(
            MenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeadNamePane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuPaneLayout.createSequentialGroup()
                .addComponent(SideOptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuPaneLayout.setVerticalGroup(
            MenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPaneLayout.createSequentialGroup()
                .addComponent(HeadNamePane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SideOptionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(MenuPane, "card3");

        pack();
    }// </editor-fold>                        

    private void RegNameActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void LogInbuttonMousePressed(java.awt.event.MouseEvent evt) {                                         
  
    }                                        

    private void ToRegisterMouseClicked(java.awt.event.MouseEvent evt) {                                        
        LogInPane.setVisible(false);
        RegistrationPane.setVisible(true);
    }                                       

    private void RegBackTextMouseClicked(java.awt.event.MouseEvent evt) {                                         
        RegistrationPane.setVisible(false);
        LogInPane.setVisible(true);
    }                                        

    private void RegSingUpTextMouseClicked(java.awt.event.MouseEvent evt) {                                           
        signUp();
    }                                          

    private void LogInbuttonMouseEntered(java.awt.event.MouseEvent evt) {                                         
        ButtonEnteredColor(LogInButtonPane, new Color(0,153,153));
    }                                        

    private void RegSingUpTextMouseEntered(java.awt.event.MouseEvent evt) {                                           
        ButtonEnteredColor(RegSignUp, new Color(0,153,153));
    }                                          

    private void RegBackTextMouseEntered(java.awt.event.MouseEvent evt) {                                         
        ButtonEnteredColor(RegBack, new Color(0,153,153));
    }                                        

    private void RegSingUpTextMouseExited(java.awt.event.MouseEvent evt) {                                          
        ButtonEnteredColor(RegSignUp, new Color(255,255,255));
    }                                         

    private void RegBackTextMouseExited(java.awt.event.MouseEvent evt) {                                        
        ButtonEnteredColor(RegBack, new Color(255,255,255));
    }                                       

    private void LogInbuttonMouseExited(java.awt.event.MouseEvent evt) {                                        
        ButtonEnteredColor(LogInButtonPane, new Color(255,255,255));
    }                                       

    private void BooksOptionTextMouseEntered(java.awt.event.MouseEvent evt) {                                             
        ButtonEnteredColor(BookOption, new Color(0,153,153));
    }                                            

    private void BooksOptionTextMouseExited(java.awt.event.MouseEvent evt) {                                            
        ButtonEnteredColor(BookOption, new Color(255,255,255));
    }                                           

    private void MyBooksOptionTextMouseEntered(java.awt.event.MouseEvent evt) {                                               
        ButtonEnteredColor(MyBooksOption, new Color(0,153,153));
    }                                              

    private void MyBooksOptionTextMouseExited(java.awt.event.MouseEvent evt) {                                              
        ButtonEnteredColor(MyBooksOption, new Color(255,255,255));
    }                                             

    private void AboutOptionTextMouseEntered(java.awt.event.MouseEvent evt) {                                             
        ButtonEnteredColor(AboutOption, new Color(0,153,153));
    }                                            

    private void AboutOptionTextMouseExited(java.awt.event.MouseEvent evt) {                                            
        ButtonEnteredColor(AboutOption, new Color(255,255,255));
    }                                           

    private void LogInbuttonMouseClicked(java.awt.event.MouseEvent evt) {                                         
        logIn();
    }                                        

    private void LogOutButtonMouseClicked(java.awt.event.MouseEvent evt) {                                          
        MenuPane.setVisible(false);
        LogInPane.setVisible(true);
    }                                         

    private void LogOutButtonMouseEntered(java.awt.event.MouseEvent evt) {                                          
        LogOutButton.setForeground(new Color(0,204,153));
    }                                         

    private void LogOutButtonMouseExited(java.awt.event.MouseEvent evt) {                                         
        LogOutButton.setForeground(new Color(255,255,255));
    }                                        

    private void BooksOptionTextMouseClicked(java.awt.event.MouseEvent evt) {                                             
        MyBooksContent.setVisible(false);
        AboutContent.setVisible(false);
        SelectedBook.setVisible(false);
        BooksCategoryContent.setVisible(true);
    }                                            

    private void MyBooksOptionTextMouseClicked(java.awt.event.MouseEvent evt) {                                               
        AboutContent.setVisible(false);
        BooksCategoryContent.setVisible(false);
        MyBooksContent.setVisible(true);
    }                                              

    private void AboutOptionTextMouseClicked(java.awt.event.MouseEvent evt) {                                             
        BooksCategoryContent.setVisible(false);
        MyBooksContent.setVisible(false);
        AboutContent.setVisible(true);
    }                                            
    
    public void ButtonEnteredColor(JPanel pane, Color color){
        pane.setBackground(color);
    }
    public void ButtonExitedColor(JPanel pane, Color color){
        pane.setBackground(color);
    }
 
    public void signUp(){
        long Id = Long.parseLong(regId.getText());
        String Fname = RegName.getText();
        String Lname = RegLname.getText();
        String email = regEmail.getText();
        String role = "";
        if(regRoleStudent.isSelected()){
            role = "student";
        } 
        else if(regRoleAdmin.isSelected()){
            role = "admin";
        }        
        String Username = RegUsername.getText();
        String Password = RegPassword.getText();
        String Re_enter_password = RegReEnterpassword.getText();
        
        if(Fname!=null && Lname!=null && Username!=null && Password!=null ){
            if(Password!=null){
                User newUser = new User(Id, Username, Password, email, role, new Date());
                em.getTransaction().begin();
                em.persist(newUser);
                em.getTransaction().commit();
                em.clear();
                JOptionPane.showMessageDialog(null, "Registered!");
                RegistrationPane.setVisible(false);
                LogInPane.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Passwords don't match!");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Enter all fields!");
        }
    }
    
    public void logIn(){
        String Logname = LogInUsername.getText();
        String Logpass = LogInPassword.getText();
        try{
            User user = em.createQuery("SELECT u FROM User u WHERE u.username = :username", User.class).setParameter("username", Logname).getSingleResult();
            if(user.getUsername().equals(Logname) && user.getPassword().equals(Logpass)){
                JOptionPane.showMessageDialog(null, "Logging in!");
                LogInPane.setVisible(false);
                MenuPane.setVisible(true);
                UserLoggedInName.setText(Logname);
            }
        }catch(NoResultException e){
            JOptionPane.showMessageDialog(null, "No such user!");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BugBusterLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BugBusterLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BugBusterLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BugBusterLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BugBusterLibraryUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel AboutContent;
    private javax.swing.JPanel AboutOption;
    private javax.swing.JLabel AboutOptionText;
    private javax.swing.JPanel BookInfo;
    private javax.swing.JPanel BookList;
    private javax.swing.JPanel BookOption;
    private javax.swing.JPanel Books;
    private javax.swing.JPanel BooksCategoryContent;
    private javax.swing.JLabel BooksOptionText;
    private javax.swing.JPanel Categories;
    private javax.swing.JLabel Category_Heading;
    private javax.swing.JPanel ContentPane;
    private javax.swing.JPanel HeadNamePane2;
    private javax.swing.JPanel HeadNamePane3;
    private javax.swing.JPanel HeadNamePane4;
    private javax.swing.JPanel LogInButtonPane;
    private javax.swing.JPanel LogInPane;
    private javax.swing.JPasswordField LogInPassword;
    private javax.swing.JTextField LogInUsername;
    private javax.swing.JLabel LogInbutton;
    private javax.swing.JLabel LogOutButton;
    private javax.swing.JPanel MenuPane;
    private javax.swing.JPanel MyBooksContent;
    private javax.swing.JPanel MyBooksOption;
    private javax.swing.JLabel MyBooksOptionText;
    private javax.swing.JPanel Reciept;
    private javax.swing.JPanel RegBack;
    private javax.swing.JLabel RegBackText;
    private javax.swing.JTextField RegLname;
    private javax.swing.JTextField RegName;
    private javax.swing.JPasswordField RegPassword;
    private javax.swing.JPasswordField RegReEnterpassword;
    private javax.swing.JPanel RegSignUp;
    private javax.swing.JLabel RegSingUpText;
    private javax.swing.JTextField RegUsername;
    private javax.swing.JPanel RegistrationPane;
    private javax.swing.JPanel SelectedBook;
    private javax.swing.JPanel SideOptionPane;
    private javax.swing.JLabel ToRegister;
    private javax.swing.JLabel UserLoggedInName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField regEmail;
    private javax.swing.JTextField regId;
    private javax.swing.JRadioButton regRoleAdmin;
    private javax.swing.JRadioButton regRoleStudent;
    // End of variables declaration                   
}
