/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bugbusterlibrary.ui;
import java.awt.Color;
import java.sql.*;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Sango
 */
public class BugBusterLibraryUI extends javax.swing.JFrame {

    /**
     * Creates new form BugBusterLibraryUI
     */
    public BugBusterLibraryUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogInPane = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogInPassword = new javax.swing.JPasswordField();
        LogInUsername = new javax.swing.JTextField();
        LogInButtonPane = new javax.swing.JPanel();
        LogInbutton = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ToRegister = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        HeadNamePane4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        RegistrationPane = new javax.swing.JPanel();
        HeadNamePane3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        RegName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        RegLname = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        regContacts = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        RegPassword = new javax.swing.JPasswordField();
        RegReEnterpassword = new javax.swing.JPasswordField();
        RegSignUp = new javax.swing.JPanel();
        RegSingUpText = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        RegBack = new javax.swing.JPanel();
        RegBackText = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RegUsername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        MenuPane = new javax.swing.JPanel();
        HeadNamePane2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LogOutButton = new javax.swing.JLabel();
        UserLoggedInName = new javax.swing.JLabel();
        SideOptionPane = new javax.swing.JPanel();
        BookOption = new javax.swing.JPanel();
        BooksOptionText = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        MyBooksOption = new javax.swing.JPanel();
        MyBooksOptionText = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        AboutOption = new javax.swing.JPanel();
        AboutOptionText = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ContentPane = new javax.swing.JPanel();
        BooksCategoryContent = new javax.swing.JPanel();
        MyBooksContent = new javax.swing.JPanel();
        AboutContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BugBuster Library");
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        LogInPane.setBackground(new java.awt.Color(62, 61, 88));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Username:");

        LogInButtonPane.setBackground(new java.awt.Color(255, 255, 255));
        LogInButtonPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 61, 88)));

        LogInbutton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LogInbutton.setText("Log In");
        LogInbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogInbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogInbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogInbuttonMousePressed(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/login_rounded_right_25px.png"))); // NOI18N

        javax.swing.GroupLayout LogInButtonPaneLayout = new javax.swing.GroupLayout(LogInButtonPane);
        LogInButtonPane.setLayout(LogInButtonPaneLayout);
        LogInButtonPaneLayout.setHorizontalGroup(
            LogInButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInButtonPaneLayout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogInbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LogInButtonPaneLayout.setVerticalGroup(
            LogInButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogInbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        ToRegister.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ToRegister.setForeground(new java.awt.Color(0, 153, 153));
        ToRegister.setText("Not a member? register.");
        ToRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToRegisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToRegister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(ToRegister)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Password:");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gender_neutral_user_40px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("LOG IN TO YOUR ACCOUNT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LogInButtonPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LogInUsername)
                                .addComponent(LogInPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(176, 176, 176))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LogInUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogInPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(LogInButtonPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        HeadNamePane4.setBackground(new java.awt.Color(62, 61, 88));
        HeadNamePane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("BugBuster Library");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/library_30px.png"))); // NOI18N

        javax.swing.GroupLayout HeadNamePane4Layout = new javax.swing.GroupLayout(HeadNamePane4);
        HeadNamePane4.setLayout(HeadNamePane4Layout);
        HeadNamePane4Layout.setHorizontalGroup(
            HeadNamePane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadNamePane4Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(HeadNamePane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeadNamePane4Layout.createSequentialGroup()
                    .addGap(290, 290, 290)
                    .addComponent(jLabel23)
                    .addContainerGap(291, Short.MAX_VALUE)))
        );
        HeadNamePane4Layout.setVerticalGroup(
            HeadNamePane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadNamePane4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel25)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(HeadNamePane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeadNamePane4Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel23)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout LogInPaneLayout = new javax.swing.GroupLayout(LogInPane);
        LogInPane.setLayout(LogInPaneLayout);
        LogInPaneLayout.setHorizontalGroup(
            LogInPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInPaneLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
            .addComponent(HeadNamePane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LogInPaneLayout.setVerticalGroup(
            LogInPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInPaneLayout.createSequentialGroup()
                .addComponent(HeadNamePane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        getContentPane().add(LogInPane, "card2");

        RegistrationPane.setBackground(new java.awt.Color(255, 255, 255));

        HeadNamePane3.setBackground(new java.awt.Color(62, 61, 88));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("BugBuster Library");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/library_30px.png"))); // NOI18N

        javax.swing.GroupLayout HeadNamePane3Layout = new javax.swing.GroupLayout(HeadNamePane3);
        HeadNamePane3.setLayout(HeadNamePane3Layout);
        HeadNamePane3Layout.setHorizontalGroup(
            HeadNamePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadNamePane3Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel16)
                .addContainerGap(499, Short.MAX_VALUE))
            .addGroup(HeadNamePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeadNamePane3Layout.createSequentialGroup()
                    .addGap(290, 290, 290)
                    .addComponent(jLabel14)
                    .addContainerGap(301, Short.MAX_VALUE)))
        );
        HeadNamePane3Layout.setVerticalGroup(
            HeadNamePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadNamePane3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(HeadNamePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeadNamePane3Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel14)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("First name:");

        RegName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegNameActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Last name:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Contacts:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Password:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Re-enter password:");

        RegSignUp.setBackground(new java.awt.Color(255, 255, 255));
        RegSignUp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 61, 88)));

        RegSingUpText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RegSingUpText.setText("Sign up");
        RegSingUpText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegSingUpTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegSingUpTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegSingUpTextMouseExited(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/login_rounded_right_25px.png"))); // NOI18N

        javax.swing.GroupLayout RegSignUpLayout = new javax.swing.GroupLayout(RegSignUp);
        RegSignUp.setLayout(RegSignUpLayout);
        RegSignUpLayout.setHorizontalGroup(
            RegSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegSignUpLayout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegSingUpText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        RegSignUpLayout.setVerticalGroup(
            RegSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegSignUpLayout.createSequentialGroup()
                .addComponent(RegSingUpText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        RegBack.setBackground(new java.awt.Color(255, 255, 255));
        RegBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(62, 61, 88)));

        RegBackText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RegBackText.setText("Back");
        RegBackText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegBackTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegBackTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegBackTextMouseExited(evt);
            }
        });

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/left_arrow_25px.png"))); // NOI18N

        javax.swing.GroupLayout RegBackLayout = new javax.swing.GroupLayout(RegBack);
        RegBack.setLayout(RegBackLayout);
        RegBackLayout.setHorizontalGroup(
            RegBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegBackLayout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegBackText, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        RegBackLayout.setVerticalGroup(
            RegBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegBackText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/gender_neutral_user_60px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Username:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("CREATE A NEW ACCOUNT");

        javax.swing.GroupLayout RegistrationPaneLayout = new javax.swing.GroupLayout(RegistrationPane);
        RegistrationPane.setLayout(RegistrationPaneLayout);
        RegistrationPaneLayout.setHorizontalGroup(
            RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeadNamePane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(RegistrationPaneLayout.createSequentialGroup()
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationPaneLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(RegistrationPaneLayout.createSequentialGroup()
                                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(RegBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegistrationPaneLayout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(RegSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(RegistrationPaneLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(RegName, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                            .addComponent(RegLname)
                                            .addComponent(regContacts)
                                            .addComponent(RegUsername)))))
                            .addGroup(RegistrationPaneLayout.createSequentialGroup()
                                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21))
                                .addGap(18, 18, 18)
                                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RegPassword)
                                    .addComponent(RegReEnterpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
                            .addGroup(RegistrationPaneLayout.createSequentialGroup()
                                .addComponent(jSeparator3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(RegistrationPaneLayout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegistrationPaneLayout.setVerticalGroup(
            RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationPaneLayout.createSequentialGroup()
                .addComponent(HeadNamePane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(RegName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(RegLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(regContacts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RegUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(RegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(RegReEnterpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(RegistrationPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RegBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        getContentPane().add(RegistrationPane, "card4");

        MenuPane.setBackground(new java.awt.Color(102, 102, 102));

        HeadNamePane2.setBackground(new java.awt.Color(62, 61, 88));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BugBuster Library");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/library_30px.png"))); // NOI18N

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("User:");

        LogOutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogOutButton.setText("Log out");
        LogOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseExited(evt);
            }
        });

        UserLoggedInName.setForeground(new java.awt.Color(0, 204, 153));

        javax.swing.GroupLayout HeadNamePane2Layout = new javax.swing.GroupLayout(HeadNamePane2);
        HeadNamePane2.setLayout(HeadNamePane2Layout);
        HeadNamePane2Layout.setHorizontalGroup(
            HeadNamePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadNamePane2Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 381, Short.MAX_VALUE)
                .addGroup(HeadNamePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadNamePane2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserLoggedInName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadNamePane2Layout.createSequentialGroup()
                        .addComponent(LogOutButton)
                        .addGap(62, 62, 62))))
            .addGroup(HeadNamePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeadNamePane2Layout.createSequentialGroup()
                    .addGap(290, 290, 290)
                    .addComponent(jLabel8)
                    .addContainerGap(301, Short.MAX_VALUE)))
        );
        HeadNamePane2Layout.setVerticalGroup(
            HeadNamePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadNamePane2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(HeadNamePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(HeadNamePane2Layout.createSequentialGroup()
                        .addGroup(HeadNamePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(UserLoggedInName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LogOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
            .addGroup(HeadNamePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HeadNamePane2Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel8)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );

        SideOptionPane.setBackground(new java.awt.Color(28, 86, 120));

        BookOption.setBackground(new java.awt.Color(255, 255, 255));

        BooksOptionText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BooksOptionText.setText("Books");
        BooksOptionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BooksOptionTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BooksOptionTextMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sorting_answers_25px.png"))); // NOI18N

        javax.swing.GroupLayout BookOptionLayout = new javax.swing.GroupLayout(BookOption);
        BookOption.setLayout(BookOptionLayout);
        BookOptionLayout.setHorizontalGroup(
            BookOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookOptionLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BooksOptionText, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
        );
        BookOptionLayout.setVerticalGroup(
            BookOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BooksOptionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        MyBooksOption.setBackground(new java.awt.Color(255, 255, 255));

        MyBooksOptionText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MyBooksOptionText.setText("My books");
        MyBooksOptionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MyBooksOptionTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MyBooksOptionTextMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/books_25px.png"))); // NOI18N

        javax.swing.GroupLayout MyBooksOptionLayout = new javax.swing.GroupLayout(MyBooksOption);
        MyBooksOption.setLayout(MyBooksOptionLayout);
        MyBooksOptionLayout.setHorizontalGroup(
            MyBooksOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyBooksOptionLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyBooksOptionText, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        MyBooksOptionLayout.setVerticalGroup(
            MyBooksOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MyBooksOptionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        AboutOption.setBackground(new java.awt.Color(255, 255, 255));

        AboutOptionText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AboutOptionText.setText("About");
        AboutOptionText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutOptionTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutOptionTextMouseExited(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/help_filled_25px.png"))); // NOI18N

        javax.swing.GroupLayout AboutOptionLayout = new javax.swing.GroupLayout(AboutOption);
        AboutOption.setLayout(AboutOptionLayout);
        AboutOptionLayout.setHorizontalGroup(
            AboutOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutOptionLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AboutOptionText, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
        );
        AboutOptionLayout.setVerticalGroup(
            AboutOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AboutOptionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SideOptionPaneLayout = new javax.swing.GroupLayout(SideOptionPane);
        SideOptionPane.setLayout(SideOptionPaneLayout);
        SideOptionPaneLayout.setHorizontalGroup(
            SideOptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideOptionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideOptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MyBooksOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideOptionPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AboutOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SideOptionPaneLayout.setVerticalGroup(
            SideOptionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideOptionPaneLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BookOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MyBooksOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AboutOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ContentPane.setBackground(new java.awt.Color(255, 255, 255));
        ContentPane.setLayout(new java.awt.CardLayout());

        BooksCategoryContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BooksCategoryContentLayout = new javax.swing.GroupLayout(BooksCategoryContent);
        BooksCategoryContent.setLayout(BooksCategoryContentLayout);
        BooksCategoryContentLayout.setHorizontalGroup(
            BooksCategoryContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        BooksCategoryContentLayout.setVerticalGroup(
            BooksCategoryContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        ContentPane.add(BooksCategoryContent, "card2");

        javax.swing.GroupLayout MyBooksContentLayout = new javax.swing.GroupLayout(MyBooksContent);
        MyBooksContent.setLayout(MyBooksContentLayout);
        MyBooksContentLayout.setHorizontalGroup(
            MyBooksContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        MyBooksContentLayout.setVerticalGroup(
            MyBooksContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        ContentPane.add(MyBooksContent, "card3");

        AboutContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout AboutContentLayout = new javax.swing.GroupLayout(AboutContent);
        AboutContent.setLayout(AboutContentLayout);
        AboutContentLayout.setHorizontalGroup(
            AboutContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        AboutContentLayout.setVerticalGroup(
            AboutContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        ContentPane.add(AboutContent, "card4");

        javax.swing.GroupLayout MenuPaneLayout = new javax.swing.GroupLayout(MenuPane);
        MenuPane.setLayout(MenuPaneLayout);
        MenuPaneLayout.setHorizontalGroup(
            MenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeadNamePane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuPaneLayout.createSequentialGroup()
                .addComponent(SideOptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuPaneLayout.setVerticalGroup(
            MenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPaneLayout.createSequentialGroup()
                .addComponent(HeadNamePane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SideOptionPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(MenuPane, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegNameActionPerformed

    private void LogInbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInbuttonMousePressed
  
    }//GEN-LAST:event_LogInbuttonMousePressed

    private void ToRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToRegisterMouseClicked
        LogInPane.setVisible(false);
        RegistrationPane.setVisible(true);
    }//GEN-LAST:event_ToRegisterMouseClicked

    private void RegBackTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegBackTextMouseClicked
        RegistrationPane.setVisible(false);
        LogInPane.setVisible(true);
    }//GEN-LAST:event_RegBackTextMouseClicked

    private void RegSingUpTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegSingUpTextMouseClicked
        String Fname = RegName.getText();
        String Lname = RegLname.getText();
        String Contacts = regContacts.getText();
        String Username = RegUsername.getText();
        String Password = RegPassword.getText();
        String Re_enter_password = RegReEnterpassword.getText();
        
        Timestamp tsmp = new Timestamp(new Date().getTime());
        
        if(Fname!=null && Lname!=null &&Contacts!=null ){
            if(Password!=null){
                try {
                    Statement ps = connect().createStatement();
                    //String query = "INSERT INTO `user`(`Fname`, `Pass`, `Date`) VALUES ('"+Fname+"','"+Password+"','"+tsmp+"')";
                    String query = "INSERT INTO `user`(`Fname`, `Lname`, `Username`, `Pass`, `Date`) VALUES ('"+Fname+"','"+Lname+"','"+Username+"','"+Password+"','"+tsmp+"')";
                    ps.execute(query);
                    JOptionPane.showMessageDialog(null, " registered!");
                    RegistrationPane.setVisible(false);
                    LogInPane.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(BugBusterLibraryUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Passwords don't match!");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Enter all fields!");
        }
    }//GEN-LAST:event_RegSingUpTextMouseClicked

    private void LogInbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInbuttonMouseEntered
        ButtonEnteredColor(LogInButtonPane, new Color(0,153,153));
    }//GEN-LAST:event_LogInbuttonMouseEntered

    private void RegSingUpTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegSingUpTextMouseEntered
        ButtonEnteredColor(RegSignUp, new Color(0,153,153));
    }//GEN-LAST:event_RegSingUpTextMouseEntered

    private void RegBackTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegBackTextMouseEntered
        ButtonEnteredColor(RegBack, new Color(0,153,153));
    }//GEN-LAST:event_RegBackTextMouseEntered

    private void RegSingUpTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegSingUpTextMouseExited
        ButtonEnteredColor(RegSignUp, new Color(255,255,255));
    }//GEN-LAST:event_RegSingUpTextMouseExited

    private void RegBackTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegBackTextMouseExited
        ButtonEnteredColor(RegBack, new Color(255,255,255));
    }//GEN-LAST:event_RegBackTextMouseExited

    private void LogInbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInbuttonMouseExited
        ButtonEnteredColor(LogInButtonPane, new Color(255,255,255));
    }//GEN-LAST:event_LogInbuttonMouseExited

    private void BooksOptionTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksOptionTextMouseEntered
        ButtonEnteredColor(BookOption, new Color(0,153,153));
    }//GEN-LAST:event_BooksOptionTextMouseEntered

    private void BooksOptionTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BooksOptionTextMouseExited
        ButtonEnteredColor(BookOption, new Color(255,255,255));
    }//GEN-LAST:event_BooksOptionTextMouseExited

    private void MyBooksOptionTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyBooksOptionTextMouseEntered
        ButtonEnteredColor(MyBooksOption, new Color(0,153,153));
    }//GEN-LAST:event_MyBooksOptionTextMouseEntered

    private void MyBooksOptionTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MyBooksOptionTextMouseExited
        ButtonEnteredColor(MyBooksOption, new Color(255,255,255));
    }//GEN-LAST:event_MyBooksOptionTextMouseExited

    private void AboutOptionTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutOptionTextMouseEntered
        ButtonEnteredColor(AboutOption, new Color(0,153,153));
    }//GEN-LAST:event_AboutOptionTextMouseEntered

    private void AboutOptionTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutOptionTextMouseExited
        ButtonEnteredColor(AboutOption, new Color(255,255,255));
    }//GEN-LAST:event_AboutOptionTextMouseExited

    private void LogInbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInbuttonMouseClicked
        String Logname = LogInUsername.getText();
        String Logpass = LogInPassword.getText();
        
        String query = "SELECT * FROM `user` WHERE `Username` =? AND `Pass` =?";
        
        try {
            PreparedStatement stmt = connect().prepareStatement(query);
            stmt.setString(1, Logname);
            stmt.setString(2, Logpass);
            ResultSet rs = stmt.executeQuery();
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Logging in!");
                LogInPane.setVisible(false);
                MenuPane.setVisible(true);
                UserLoggedInName.setText(Logname);
            }else{
                JOptionPane.showMessageDialog(null,"Incorrect username or password!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(BugBusterLibraryUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LogInbuttonMouseClicked

    private void LogOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutButtonMouseClicked
        MenuPane.setVisible(false);
        LogInPane.setVisible(true);
    }//GEN-LAST:event_LogOutButtonMouseClicked

    private void LogOutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutButtonMouseEntered
        LogOutButton.setForeground(new Color(0,204,153));
    }//GEN-LAST:event_LogOutButtonMouseEntered

    private void LogOutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutButtonMouseExited
        LogOutButton.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_LogOutButtonMouseExited
    public void ButtonEnteredColor(JPanel pane, Color color){
        pane.setBackground(color);
    }
    public void ButtonExitedColor(JPanel pane, Color color){
        pane.setBackground(color);
    }
    private Connection connect(){
        final String username = "sql10433996";
        final String password = "s3Kr2BgYbp";
        final String connection = "jdbc:mysql://sql10.freemysqlhosting.net/sql10433996";
        Connection conn = null;
        try{
            conn = DriverManager.getConnection(connection, username, password);
        }
        catch(SQLException e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return conn;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BugBusterLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BugBusterLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BugBusterLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BugBusterLibraryUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BugBusterLibraryUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutContent;
    private javax.swing.JPanel AboutOption;
    private javax.swing.JLabel AboutOptionText;
    private javax.swing.JPanel BookOption;
    private javax.swing.JPanel BooksCategoryContent;
    private javax.swing.JLabel BooksOptionText;
    private javax.swing.JPanel ContentPane;
    private javax.swing.JPanel HeadNamePane2;
    private javax.swing.JPanel HeadNamePane3;
    private javax.swing.JPanel HeadNamePane4;
    private javax.swing.JPanel LogInButtonPane;
    private javax.swing.JPanel LogInPane;
    private javax.swing.JPasswordField LogInPassword;
    private javax.swing.JTextField LogInUsername;
    private javax.swing.JLabel LogInbutton;
    private javax.swing.JLabel LogOutButton;
    private javax.swing.JPanel MenuPane;
    private javax.swing.JPanel MyBooksContent;
    private javax.swing.JPanel MyBooksOption;
    private javax.swing.JLabel MyBooksOptionText;
    private javax.swing.JPanel RegBack;
    private javax.swing.JLabel RegBackText;
    private javax.swing.JTextField RegLname;
    private javax.swing.JTextField RegName;
    private javax.swing.JPasswordField RegPassword;
    private javax.swing.JPasswordField RegReEnterpassword;
    private javax.swing.JPanel RegSignUp;
    private javax.swing.JLabel RegSingUpText;
    private javax.swing.JTextField RegUsername;
    private javax.swing.JPanel RegistrationPane;
    private javax.swing.JPanel SideOptionPane;
    private javax.swing.JLabel ToRegister;
    private javax.swing.JLabel UserLoggedInName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField regContacts;
    // End of variables declaration//GEN-END:variables
}
